### ISSUE TITLE
Extension fails to activate. Throws error

### ISSUE THREAD

**Issue by jmigual** [prosser/json-schema-validation-extension#6]
The extension fails to activate. See the log output:

<details>
<summary>Log output</summary>

```
2023-05-09 16:52:47.936 [info] ExtensionService#_doActivateExtension prosser.json-schema-2020-validation, startup: false, activationEvent: 'onLanguage:json'
2023-05-09 16:52:47.947 [error] Activating extension prosser.json-schema-2020-validation failed due to an error:
2023-05-09 16:52:47.947 [error] Error: Cannot find module 'c:\Users\<user>\.vscode\extensions\prosser.json-schema-2020-validation-0.0.5\out\extension'
Require stack:
- c:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js
- c:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-amd.js
- c:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:1010:15)
    at Function.s._resolveFilename (node:electron/js2c/utility_init:2:2740)
    at Module._load (node:internal/modules/cjs/loader:858:27)
    at Function.f._load (node:electron/js2c/asar_bundle:2:13330)
    at Function.b._load (c:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:126:29948)
    at Function.h._load (c:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:126:26698)
    at Function.I._load (c:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:90:24489)
    at Module.apply (node:internal/modules/cjs/loader:1082:19)
    at Module.require (c:\Users\<user>\.vscode\extensions\julialang.language-julia-1.38.2\node_modules\diagnostic-channel\dist\src\patchRequire.js:16:46)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Function.i [as __$__nodeRequire] (c:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:5:98)
    at v.rb (c:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:126:27962)
    at async Promise.all (index 0)
```

</details>

**Comment by prosser** [comment]
Which OS version are you using? I'm presuming Windows with that stack trace.

**Comment by alecxvs** [comment]
Though I'm running it in a remote linux host, I get an identical error:
```
2023-06-13 00:46:28.112 [info] ExtensionService#_doActivateExtension prosser.json-schema-2020-validation, startup: false, activationEvent: 'onLanguage:json'
2023-06-13 00:46:28.364 [error] Activating extension prosser.json-schema-2020-validation failed due to an error:
2023-06-13 00:46:28.364 [error] Error: Cannot find module '/root/.vscode-server/extensions/prosser.json-schema-2020-validation-0.0.5/out/extension'
Require stack:
- /root/.vscode-server/bin/b380da4ef1ee00e224a15c1d4d9793e27c2b6302/out/vs/loader.js
- /root/.vscode-server/bin/b380da4ef1ee00e224a15c1d4d9793e27c2b6302/out/bootstrap-amd.js
- /root/.vscode-server/bin/b380da4ef1ee00e224a15c1d4d9793e27c2b6302/out/bootstrap-fork.js
	at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
	at Function.Module._load (node:internal/modules/cjs/loader:804:27)
	at Function.f._load (/root/.vscode-server/bin/b380da4ef1ee00e224a15c1d4d9793e27c2b6302/out/vs/workbench/api/node/extensionHostProcess.js:128:30006)
	at Function.E._load (/root/.vscode-server/bin/b380da4ef1ee00e224a15c1d4d9793e27c2b6302/out/vs/workbench/api/node/extensionHostProcess.js:128:26701)
	at Function.C._load (/root/.vscode-server/bin/b380da4ef1ee00e224a15c1d4d9793e27c2b6302/out/vs/workbench/api/node/extensionHostProcess.js:92:24636)
	at Module.require (node:internal/modules/cjs/loader:1028:19)
	at require (node:internal/modules/cjs/helpers:102:18)
	at Function.i [as __$__nodeRequire] (/root/.vscode-server/bin/b380da4ef1ee00e224a15c1d4d9793e27c2b6302/out/vs/loader.js:5:98)
	at n.sb (/root/.vscode-server/bin/b380da4ef1ee00e224a15c1d4d9793e27c2b6302/out/vs/workbench/api/node/extensionHostProcess.js:128:28020)
	at async Promise.all (index 0)
```

**Comment by alecxvs** [comment]
Might be the same as https://github.com/prosser/json-schema-validation-extension/issues/4

**Comment by fenix31415** [comment]
Confirm

**Comment by yoiang** [comment]
I'm having the same issue unfortunately!
